//animation 🪁

const DURATION_TIME_LENGTH = 200;
const DELAY_SCALING_TIME = 2000;
const DURATION_SCALING_ICON = 750;
const MAX_SCALING_ICON = 1.1;
const MIN_SCALING_ICON = 1;

//colors 🌈
const PRIMARY_COLOR = "#00ACBB";
const SECONDARY_COLOR = "rgba(0,0,0,0.5)";

//font
const LING_HIEGHT_NAV = 6;
const FONT_SIZE_ICON = 12;

export {
  DURATION_TIME_LENGTH,
  DURATION_SCALING_ICON,
  MAX_SCALING_ICON,
  MIN_SCALING_ICON,
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  FONT_SIZE_ICON,
  DELAY_SCALING_TIME,
  LING_HIEGHT_NAV,
};
